gerrit_host: "azvyagintsev@review.fuel-infra.org"
targets:
  openstack:
    prefixes:
     - "openstack/"
#     - "openstack-build/"
    branches_all:
      - "mcp/pike"
    # those project doesn't have sources.Mostly - not openstack packages
    project_blacklist1:
#    project_custom_branches:
#      openstack/fuel-nailgun-extension-converted-serializers: ["stable/mitaka"]
#      openstack/fuel-nailgun-extension-iac: [ "stable/mitaka" ]
#      openstack/timmy: ["stable/mitaka"]
  specs:
    prefixes:
     - "packaging/specs/"
    branches_all:
      - "mcp/pike"
