targets:
  openstack:
    prefixes:
     - "openstack/"
#     - "openstack-build/"
    branches_all:
      - "mcp/pike"
#    project_custom_branches:
#      openstack/fuel-nailgun-extension-converted-serializers: ["stable/mitaka"]
#      openstack/fuel-nailgun-extension-iac: [ "stable/mitaka" ]
#      openstack/timmy: ["stable/mitaka"]
  specs:
    prefixes:
     - "packaging/specs/"
    branches_all:
      - "mcp/pike"

